// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_messages.proto

package edu.usfca.cs.dfs;

public final class StorageMessages {
  private StorageMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code messageType}
   */
  public enum messageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FIND_HOST = 0;</code>
     */
    FIND_HOST(0),
    /**
     * <code>DATA = 1;</code>
     */
    DATA(1),
    /**
     * <code>ACK = 2;</code>
     */
    ACK(2),
    /**
     * <code>INFO = 3;</code>
     */
    INFO(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>FIND_HOST = 0;</code>
     */
    public static final int FIND_HOST_VALUE = 0;
    /**
     * <code>DATA = 1;</code>
     */
    public static final int DATA_VALUE = 1;
    /**
     * <code>ACK = 2;</code>
     */
    public static final int ACK_VALUE = 2;
    /**
     * <code>INFO = 3;</code>
     */
    public static final int INFO_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static messageType valueOf(int value) {
      return forNumber(value);
    }

    public static messageType forNumber(int value) {
      switch (value) {
        case 0: return FIND_HOST;
        case 1: return DATA;
        case 2: return ACK;
        case 3: return INFO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<messageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        messageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<messageType>() {
            public messageType findValueByNumber(int number) {
              return messageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.StorageMessages.getDescriptor().getEnumTypes().get(0);
    }

    private static final messageType[] VALUES = values();

    public static messageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private messageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:messageType)
  }

  /**
   * Protobuf enum {@code infoType}
   */
  public enum infoType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * list all nodes in chord network
     * </pre>
     *
     * <code>LIST_NODE = 0;</code>
     */
    LIST_NODE(0),
    /**
     * <pre>
     * check remaining disk space
     * </pre>
     *
     * <code>DISK_SPACE = 1;</code>
     */
    DISK_SPACE(1),
    /**
     * <pre>
     * check number of total requests received
     * </pre>
     *
     * <code>NUM_REQUESTS = 2;</code>
     */
    NUM_REQUESTS(2),
    /**
     * <pre>
     * list all file name
     * </pre>
     *
     * <code>LIST_FILES = 3;</code>
     */
    LIST_FILES(3),
    /**
     * <pre>
     * get total number of chunks of a particular file
     * </pre>
     *
     * <code>NUM_CHUNKS = 4;</code>
     */
    NUM_CHUNKS(4),
    /**
     * <pre>
     * get all chunk location of a particular file
     * </pre>
     *
     * <code>CHUNK_LOCATION = 5;</code>
     */
    CHUNK_LOCATION(5),
    /**
     * <pre>
     * retrieve a chunk
     * </pre>
     *
     * <code>RETRIEVE_CHUNK = 6;</code>
     */
    RETRIEVE_CHUNK(6),
    /**
     * <pre>
     * finger table
     * </pre>
     *
     * <code>FINGER = 7;</code>
     */
    FINGER(7),
    /**
     * <code>PREDECESSOR = 8;</code>
     */
    PREDECESSOR(8),
    /**
     * <pre>
     * update finger table request
     * </pre>
     *
     * <code>UPDATE = 9;</code>
     */
    UPDATE(9),
    /**
     * <pre>
     * ask for the closest preceding finger
     * </pre>
     *
     * <code>CLOSEST_PRECEDING_FINGER = 10;</code>
     */
    CLOSEST_PRECEDING_FINGER(10),
    /**
     * <pre>
     * reply closest preceding finger
     * </pre>
     *
     * <code>NODE = 11;</code>
     */
    NODE(11),
    /**
     * <pre>
     * ask for the m parameter
     * </pre>
     *
     * <code>ASK_M = 12;</code>
     */
    ASK_M(12),
    /**
     * <pre>
     * m-bit ring
     * </pre>
     *
     * <code>M = 13;</code>
     */
    M(13),
    /**
     * <pre>
     * find successor of particular id
     * </pre>
     *
     * <code>ASK_SUCCESSOR = 14;</code>
     */
    ASK_SUCCESSOR(14),
    /**
     * <pre>
     * get the detail of the node been asked
     * </pre>
     *
     * <code>ASK_NODE_DETAIL = 15;</code>
     */
    ASK_NODE_DETAIL(15),
    /**
     * <code>UPDATE_PREDECESSOR = 16;</code>
     */
    UPDATE_PREDECESSOR(16),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * list all nodes in chord network
     * </pre>
     *
     * <code>LIST_NODE = 0;</code>
     */
    public static final int LIST_NODE_VALUE = 0;
    /**
     * <pre>
     * check remaining disk space
     * </pre>
     *
     * <code>DISK_SPACE = 1;</code>
     */
    public static final int DISK_SPACE_VALUE = 1;
    /**
     * <pre>
     * check number of total requests received
     * </pre>
     *
     * <code>NUM_REQUESTS = 2;</code>
     */
    public static final int NUM_REQUESTS_VALUE = 2;
    /**
     * <pre>
     * list all file name
     * </pre>
     *
     * <code>LIST_FILES = 3;</code>
     */
    public static final int LIST_FILES_VALUE = 3;
    /**
     * <pre>
     * get total number of chunks of a particular file
     * </pre>
     *
     * <code>NUM_CHUNKS = 4;</code>
     */
    public static final int NUM_CHUNKS_VALUE = 4;
    /**
     * <pre>
     * get all chunk location of a particular file
     * </pre>
     *
     * <code>CHUNK_LOCATION = 5;</code>
     */
    public static final int CHUNK_LOCATION_VALUE = 5;
    /**
     * <pre>
     * retrieve a chunk
     * </pre>
     *
     * <code>RETRIEVE_CHUNK = 6;</code>
     */
    public static final int RETRIEVE_CHUNK_VALUE = 6;
    /**
     * <pre>
     * finger table
     * </pre>
     *
     * <code>FINGER = 7;</code>
     */
    public static final int FINGER_VALUE = 7;
    /**
     * <code>PREDECESSOR = 8;</code>
     */
    public static final int PREDECESSOR_VALUE = 8;
    /**
     * <pre>
     * update finger table request
     * </pre>
     *
     * <code>UPDATE = 9;</code>
     */
    public static final int UPDATE_VALUE = 9;
    /**
     * <pre>
     * ask for the closest preceding finger
     * </pre>
     *
     * <code>CLOSEST_PRECEDING_FINGER = 10;</code>
     */
    public static final int CLOSEST_PRECEDING_FINGER_VALUE = 10;
    /**
     * <pre>
     * reply closest preceding finger
     * </pre>
     *
     * <code>NODE = 11;</code>
     */
    public static final int NODE_VALUE = 11;
    /**
     * <pre>
     * ask for the m parameter
     * </pre>
     *
     * <code>ASK_M = 12;</code>
     */
    public static final int ASK_M_VALUE = 12;
    /**
     * <pre>
     * m-bit ring
     * </pre>
     *
     * <code>M = 13;</code>
     */
    public static final int M_VALUE = 13;
    /**
     * <pre>
     * find successor of particular id
     * </pre>
     *
     * <code>ASK_SUCCESSOR = 14;</code>
     */
    public static final int ASK_SUCCESSOR_VALUE = 14;
    /**
     * <pre>
     * get the detail of the node been asked
     * </pre>
     *
     * <code>ASK_NODE_DETAIL = 15;</code>
     */
    public static final int ASK_NODE_DETAIL_VALUE = 15;
    /**
     * <code>UPDATE_PREDECESSOR = 16;</code>
     */
    public static final int UPDATE_PREDECESSOR_VALUE = 16;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static infoType valueOf(int value) {
      return forNumber(value);
    }

    public static infoType forNumber(int value) {
      switch (value) {
        case 0: return LIST_NODE;
        case 1: return DISK_SPACE;
        case 2: return NUM_REQUESTS;
        case 3: return LIST_FILES;
        case 4: return NUM_CHUNKS;
        case 5: return CHUNK_LOCATION;
        case 6: return RETRIEVE_CHUNK;
        case 7: return FINGER;
        case 8: return PREDECESSOR;
        case 9: return UPDATE;
        case 10: return CLOSEST_PRECEDING_FINGER;
        case 11: return NODE;
        case 12: return ASK_M;
        case 13: return M;
        case 14: return ASK_SUCCESSOR;
        case 15: return ASK_NODE_DETAIL;
        case 16: return UPDATE_PREDECESSOR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<infoType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        infoType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<infoType>() {
            public infoType findValueByNumber(int number) {
              return infoType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.StorageMessages.getDescriptor().getEnumTypes().get(1);
    }

    private static final infoType[] VALUES = values();

    public static infoType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private infoType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:infoType)
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.messageType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.messageType type = 1;</code>
     */
    edu.usfca.cs.dfs.StorageMessages.messageType getType();

    /**
     * <code>string fileName = 2;</code>
     */
    java.lang.String getFileName();
    /**
     * <code>string fileName = 2;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>int32 totalChunk = 3;</code>
     */
    int getTotalChunk();

    /**
     * <code>int32 chunkId = 4;</code>
     */
    int getChunkId();

    /**
     * <code>bytes data = 5;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      type_ = 0;
      fileName_ = "";
      totalChunk_ = 0;
      chunkId_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            case 24: {

              totalChunk_ = input.readInt32();
              break;
            }
            case 32: {

              chunkId_ = input.readInt32();
              break;
            }
            case 42: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.StorageMessages.internal_static_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.StorageMessages.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.StorageMessages.Message.class, edu.usfca.cs.dfs.StorageMessages.Message.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.messageType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.messageType type = 1;</code>
     */
    public edu.usfca.cs.dfs.StorageMessages.messageType getType() {
      @SuppressWarnings("deprecation")
      edu.usfca.cs.dfs.StorageMessages.messageType result = edu.usfca.cs.dfs.StorageMessages.messageType.valueOf(type_);
      return result == null ? edu.usfca.cs.dfs.StorageMessages.messageType.UNRECOGNIZED : result;
    }

    public static final int FILENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object fileName_;
    /**
     * <code>string fileName = 2;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string fileName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOTALCHUNK_FIELD_NUMBER = 3;
    private int totalChunk_;
    /**
     * <code>int32 totalChunk = 3;</code>
     */
    public int getTotalChunk() {
      return totalChunk_;
    }

    public static final int CHUNKID_FIELD_NUMBER = 4;
    private int chunkId_;
    /**
     * <code>int32 chunkId = 4;</code>
     */
    public int getChunkId() {
      return chunkId_;
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 5;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != edu.usfca.cs.dfs.StorageMessages.messageType.FIND_HOST.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getFileNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fileName_);
      }
      if (totalChunk_ != 0) {
        output.writeInt32(3, totalChunk_);
      }
      if (chunkId_ != 0) {
        output.writeInt32(4, chunkId_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(5, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != edu.usfca.cs.dfs.StorageMessages.messageType.FIND_HOST.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getFileNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fileName_);
      }
      if (totalChunk_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, totalChunk_);
      }
      if (chunkId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, chunkId_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.StorageMessages.Message)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.StorageMessages.Message other = (edu.usfca.cs.dfs.StorageMessages.Message) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getFileName()
          .equals(other.getFileName());
      result = result && (getTotalChunk()
          == other.getTotalChunk());
      result = result && (getChunkId()
          == other.getChunkId());
      result = result && getData()
          .equals(other.getData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + TOTALCHUNK_FIELD_NUMBER;
      hash = (53 * hash) + getTotalChunk();
      hash = (37 * hash) + CHUNKID_FIELD_NUMBER;
      hash = (53 * hash) + getChunkId();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.StorageMessages.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.StorageMessages.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        edu.usfca.cs.dfs.StorageMessages.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.StorageMessages.Message.class, edu.usfca.cs.dfs.StorageMessages.Message.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.StorageMessages.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        fileName_ = "";

        totalChunk_ = 0;

        chunkId_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_Message_descriptor;
      }

      @java.lang.Override
      public edu.usfca.cs.dfs.StorageMessages.Message getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.StorageMessages.Message.getDefaultInstance();
      }

      @java.lang.Override
      public edu.usfca.cs.dfs.StorageMessages.Message build() {
        edu.usfca.cs.dfs.StorageMessages.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public edu.usfca.cs.dfs.StorageMessages.Message buildPartial() {
        edu.usfca.cs.dfs.StorageMessages.Message result = new edu.usfca.cs.dfs.StorageMessages.Message(this);
        result.type_ = type_;
        result.fileName_ = fileName_;
        result.totalChunk_ = totalChunk_;
        result.chunkId_ = chunkId_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.StorageMessages.Message) {
          return mergeFrom((edu.usfca.cs.dfs.StorageMessages.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.StorageMessages.Message other) {
        if (other == edu.usfca.cs.dfs.StorageMessages.Message.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.getTotalChunk() != 0) {
          setTotalChunk(other.getTotalChunk());
        }
        if (other.getChunkId() != 0) {
          setChunkId(other.getChunkId());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.StorageMessages.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.StorageMessages.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.messageType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.messageType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.messageType type = 1;</code>
       */
      public edu.usfca.cs.dfs.StorageMessages.messageType getType() {
        @SuppressWarnings("deprecation")
        edu.usfca.cs.dfs.StorageMessages.messageType result = edu.usfca.cs.dfs.StorageMessages.messageType.valueOf(type_);
        return result == null ? edu.usfca.cs.dfs.StorageMessages.messageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.messageType type = 1;</code>
       */
      public Builder setType(edu.usfca.cs.dfs.StorageMessages.messageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.messageType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <code>string fileName = 2;</code>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fileName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileName = 2;</code>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 2;</code>
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 2;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }

      private int totalChunk_ ;
      /**
       * <code>int32 totalChunk = 3;</code>
       */
      public int getTotalChunk() {
        return totalChunk_;
      }
      /**
       * <code>int32 totalChunk = 3;</code>
       */
      public Builder setTotalChunk(int value) {
        
        totalChunk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 totalChunk = 3;</code>
       */
      public Builder clearTotalChunk() {
        
        totalChunk_ = 0;
        onChanged();
        return this;
      }

      private int chunkId_ ;
      /**
       * <code>int32 chunkId = 4;</code>
       */
      public int getChunkId() {
        return chunkId_;
      }
      /**
       * <code>int32 chunkId = 4;</code>
       */
      public Builder setChunkId(int value) {
        
        chunkId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 chunkId = 4;</code>
       */
      public Builder clearChunkId() {
        
        chunkId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 5;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 5;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 5;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final edu.usfca.cs.dfs.StorageMessages.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.StorageMessages.Message();
    }

    public static edu.usfca.cs.dfs.StorageMessages.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public edu.usfca.cs.dfs.StorageMessages.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Info)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.infoType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.infoType type = 1;</code>
     */
    edu.usfca.cs.dfs.StorageMessages.infoType getType();

    /**
     * <code>bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>string time = 3;</code>
     */
    java.lang.String getTime();
    /**
     * <code>string time = 3;</code>
     */
    com.google.protobuf.ByteString
        getTimeBytes();
  }
  /**
   * Protobuf type {@code Info}
   */
  public  static final class Info extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Info)
      InfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Info.newBuilder() to construct.
    private Info(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Info() {
      type_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
      time_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Info(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              time_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.StorageMessages.internal_static_Info_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.StorageMessages.internal_static_Info_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.StorageMessages.Info.class, edu.usfca.cs.dfs.StorageMessages.Info.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.infoType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.infoType type = 1;</code>
     */
    public edu.usfca.cs.dfs.StorageMessages.infoType getType() {
      @SuppressWarnings("deprecation")
      edu.usfca.cs.dfs.StorageMessages.infoType result = edu.usfca.cs.dfs.StorageMessages.infoType.valueOf(type_);
      return result == null ? edu.usfca.cs.dfs.StorageMessages.infoType.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private volatile java.lang.Object time_;
    /**
     * <code>string time = 3;</code>
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        time_ = s;
        return s;
      }
    }
    /**
     * <code>string time = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != edu.usfca.cs.dfs.StorageMessages.infoType.LIST_NODE.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
      if (!getTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, time_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != edu.usfca.cs.dfs.StorageMessages.infoType.LIST_NODE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      if (!getTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, time_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.StorageMessages.Info)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.StorageMessages.Info other = (edu.usfca.cs.dfs.StorageMessages.Info) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getData()
          .equals(other.getData());
      result = result && getTime()
          .equals(other.getTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.StorageMessages.Info parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Info parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Info parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Info parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Info parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Info parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Info parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Info parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Info parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Info parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Info parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Info parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.StorageMessages.Info prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Info}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Info)
        edu.usfca.cs.dfs.StorageMessages.InfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_Info_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_Info_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.StorageMessages.Info.class, edu.usfca.cs.dfs.StorageMessages.Info.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.StorageMessages.Info.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        time_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_Info_descriptor;
      }

      @java.lang.Override
      public edu.usfca.cs.dfs.StorageMessages.Info getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.StorageMessages.Info.getDefaultInstance();
      }

      @java.lang.Override
      public edu.usfca.cs.dfs.StorageMessages.Info build() {
        edu.usfca.cs.dfs.StorageMessages.Info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public edu.usfca.cs.dfs.StorageMessages.Info buildPartial() {
        edu.usfca.cs.dfs.StorageMessages.Info result = new edu.usfca.cs.dfs.StorageMessages.Info(this);
        result.type_ = type_;
        result.data_ = data_;
        result.time_ = time_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.StorageMessages.Info) {
          return mergeFrom((edu.usfca.cs.dfs.StorageMessages.Info)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.StorageMessages.Info other) {
        if (other == edu.usfca.cs.dfs.StorageMessages.Info.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (!other.getTime().isEmpty()) {
          time_ = other.time_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.StorageMessages.Info parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.StorageMessages.Info) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.infoType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.infoType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.infoType type = 1;</code>
       */
      public edu.usfca.cs.dfs.StorageMessages.infoType getType() {
        @SuppressWarnings("deprecation")
        edu.usfca.cs.dfs.StorageMessages.infoType result = edu.usfca.cs.dfs.StorageMessages.infoType.valueOf(type_);
        return result == null ? edu.usfca.cs.dfs.StorageMessages.infoType.UNRECOGNIZED : result;
      }
      /**
       * <code>.infoType type = 1;</code>
       */
      public Builder setType(edu.usfca.cs.dfs.StorageMessages.infoType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.infoType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private java.lang.Object time_ = "";
      /**
       * <code>string time = 3;</code>
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string time = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string time = 3;</code>
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string time = 3;</code>
       */
      public Builder clearTime() {
        
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>string time = 3;</code>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        time_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Info)
    }

    // @@protoc_insertion_point(class_scope:Info)
    private static final edu.usfca.cs.dfs.StorageMessages.Info DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.StorageMessages.Info();
    }

    public static edu.usfca.cs.dfs.StorageMessages.Info getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Info>
        PARSER = new com.google.protobuf.AbstractParser<Info>() {
      @java.lang.Override
      public Info parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Info(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Info> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Info> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public edu.usfca.cs.dfs.StorageMessages.Info getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Node)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string host = 1;</code>
     */
    java.lang.String getHost();
    /**
     * <code>string host = 1;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>int32 port = 2;</code>
     */
    int getPort();

    /**
     * <code>int32 id = 3;</code>
     */
    int getId();

    /**
     * <code>string successor = 4;</code>
     */
    java.lang.String getSuccessor();
    /**
     * <code>string successor = 4;</code>
     */
    com.google.protobuf.ByteString
        getSuccessorBytes();

    /**
     * <code>int32 successorId = 5;</code>
     */
    int getSuccessorId();

    /**
     * <code>string predecessor = 6;</code>
     */
    java.lang.String getPredecessor();
    /**
     * <code>string predecessor = 6;</code>
     */
    com.google.protobuf.ByteString
        getPredecessorBytes();
  }
  /**
   * Protobuf type {@code Node}
   */
  public  static final class Node extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Node)
      NodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Node.newBuilder() to construct.
    private Node(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Node() {
      host_ = "";
      port_ = 0;
      id_ = 0;
      successor_ = "";
      successorId_ = 0;
      predecessor_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Node(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 16: {

              port_ = input.readInt32();
              break;
            }
            case 24: {

              id_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              successor_ = s;
              break;
            }
            case 40: {

              successorId_ = input.readInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              predecessor_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.StorageMessages.internal_static_Node_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.StorageMessages.internal_static_Node_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.StorageMessages.Node.class, edu.usfca.cs.dfs.StorageMessages.Node.Builder.class);
    }

    public static final int HOST_FIELD_NUMBER = 1;
    private volatile java.lang.Object host_;
    /**
     * <code>string host = 1;</code>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <code>string host = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <code>int32 port = 2;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int ID_FIELD_NUMBER = 3;
    private int id_;
    /**
     * <code>int32 id = 3;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int SUCCESSOR_FIELD_NUMBER = 4;
    private volatile java.lang.Object successor_;
    /**
     * <code>string successor = 4;</code>
     */
    public java.lang.String getSuccessor() {
      java.lang.Object ref = successor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        successor_ = s;
        return s;
      }
    }
    /**
     * <code>string successor = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSuccessorBytes() {
      java.lang.Object ref = successor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        successor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUCCESSORID_FIELD_NUMBER = 5;
    private int successorId_;
    /**
     * <code>int32 successorId = 5;</code>
     */
    public int getSuccessorId() {
      return successorId_;
    }

    public static final int PREDECESSOR_FIELD_NUMBER = 6;
    private volatile java.lang.Object predecessor_;
    /**
     * <code>string predecessor = 6;</code>
     */
    public java.lang.String getPredecessor() {
      java.lang.Object ref = predecessor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        predecessor_ = s;
        return s;
      }
    }
    /**
     * <code>string predecessor = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPredecessorBytes() {
      java.lang.Object ref = predecessor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        predecessor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, host_);
      }
      if (port_ != 0) {
        output.writeInt32(2, port_);
      }
      if (id_ != 0) {
        output.writeInt32(3, id_);
      }
      if (!getSuccessorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, successor_);
      }
      if (successorId_ != 0) {
        output.writeInt32(5, successorId_);
      }
      if (!getPredecessorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, predecessor_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, host_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, port_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, id_);
      }
      if (!getSuccessorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, successor_);
      }
      if (successorId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, successorId_);
      }
      if (!getPredecessorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, predecessor_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.StorageMessages.Node)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.StorageMessages.Node other = (edu.usfca.cs.dfs.StorageMessages.Node) obj;

      boolean result = true;
      result = result && getHost()
          .equals(other.getHost());
      result = result && (getPort()
          == other.getPort());
      result = result && (getId()
          == other.getId());
      result = result && getSuccessor()
          .equals(other.getSuccessor());
      result = result && (getSuccessorId()
          == other.getSuccessorId());
      result = result && getPredecessor()
          .equals(other.getPredecessor());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + SUCCESSOR_FIELD_NUMBER;
      hash = (53 * hash) + getSuccessor().hashCode();
      hash = (37 * hash) + SUCCESSORID_FIELD_NUMBER;
      hash = (53 * hash) + getSuccessorId();
      hash = (37 * hash) + PREDECESSOR_FIELD_NUMBER;
      hash = (53 * hash) + getPredecessor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.StorageMessages.Node parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Node parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Node parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Node parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Node parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Node parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Node parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Node parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Node parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Node parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Node parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.Node parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.StorageMessages.Node prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Node}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Node)
        edu.usfca.cs.dfs.StorageMessages.NodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_Node_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_Node_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.StorageMessages.Node.class, edu.usfca.cs.dfs.StorageMessages.Node.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.StorageMessages.Node.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        host_ = "";

        port_ = 0;

        id_ = 0;

        successor_ = "";

        successorId_ = 0;

        predecessor_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_Node_descriptor;
      }

      @java.lang.Override
      public edu.usfca.cs.dfs.StorageMessages.Node getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.StorageMessages.Node.getDefaultInstance();
      }

      @java.lang.Override
      public edu.usfca.cs.dfs.StorageMessages.Node build() {
        edu.usfca.cs.dfs.StorageMessages.Node result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public edu.usfca.cs.dfs.StorageMessages.Node buildPartial() {
        edu.usfca.cs.dfs.StorageMessages.Node result = new edu.usfca.cs.dfs.StorageMessages.Node(this);
        result.host_ = host_;
        result.port_ = port_;
        result.id_ = id_;
        result.successor_ = successor_;
        result.successorId_ = successorId_;
        result.predecessor_ = predecessor_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.StorageMessages.Node) {
          return mergeFrom((edu.usfca.cs.dfs.StorageMessages.Node)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.StorageMessages.Node other) {
        if (other == edu.usfca.cs.dfs.StorageMessages.Node.getDefaultInstance()) return this;
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getSuccessor().isEmpty()) {
          successor_ = other.successor_;
          onChanged();
        }
        if (other.getSuccessorId() != 0) {
          setSuccessorId(other.getSuccessorId());
        }
        if (!other.getPredecessor().isEmpty()) {
          predecessor_ = other.predecessor_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.StorageMessages.Node parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.StorageMessages.Node) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object host_ = "";
      /**
       * <code>string host = 1;</code>
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string host = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string host = 1;</code>
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string host = 1;</code>
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>string host = 1;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 2;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 2;</code>
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 2;</code>
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 3;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 3;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 3;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object successor_ = "";
      /**
       * <code>string successor = 4;</code>
       */
      public java.lang.String getSuccessor() {
        java.lang.Object ref = successor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          successor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string successor = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSuccessorBytes() {
        java.lang.Object ref = successor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          successor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string successor = 4;</code>
       */
      public Builder setSuccessor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        successor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string successor = 4;</code>
       */
      public Builder clearSuccessor() {
        
        successor_ = getDefaultInstance().getSuccessor();
        onChanged();
        return this;
      }
      /**
       * <code>string successor = 4;</code>
       */
      public Builder setSuccessorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        successor_ = value;
        onChanged();
        return this;
      }

      private int successorId_ ;
      /**
       * <code>int32 successorId = 5;</code>
       */
      public int getSuccessorId() {
        return successorId_;
      }
      /**
       * <code>int32 successorId = 5;</code>
       */
      public Builder setSuccessorId(int value) {
        
        successorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 successorId = 5;</code>
       */
      public Builder clearSuccessorId() {
        
        successorId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object predecessor_ = "";
      /**
       * <code>string predecessor = 6;</code>
       */
      public java.lang.String getPredecessor() {
        java.lang.Object ref = predecessor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          predecessor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string predecessor = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPredecessorBytes() {
        java.lang.Object ref = predecessor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          predecessor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string predecessor = 6;</code>
       */
      public Builder setPredecessor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        predecessor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string predecessor = 6;</code>
       */
      public Builder clearPredecessor() {
        
        predecessor_ = getDefaultInstance().getPredecessor();
        onChanged();
        return this;
      }
      /**
       * <code>string predecessor = 6;</code>
       */
      public Builder setPredecessorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        predecessor_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Node)
    }

    // @@protoc_insertion_point(class_scope:Node)
    private static final edu.usfca.cs.dfs.StorageMessages.Node DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.StorageMessages.Node();
    }

    public static edu.usfca.cs.dfs.StorageMessages.Node getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Node>
        PARSER = new com.google.protobuf.AbstractParser<Node>() {
      @java.lang.Override
      public Node parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Node(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Node> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Node> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public edu.usfca.cs.dfs.StorageMessages.Node getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Info_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Info_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Node_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Node_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026storage_messages.proto\"j\n\007Message\022\032\n\004t" +
      "ype\030\001 \001(\0162\014.messageType\022\020\n\010fileName\030\002 \001(" +
      "\t\022\022\n\ntotalChunk\030\003 \001(\005\022\017\n\007chunkId\030\004 \001(\005\022\014" +
      "\n\004data\030\005 \001(\014\";\n\004Info\022\027\n\004type\030\001 \001(\0162\t.inf" +
      "oType\022\014\n\004data\030\002 \001(\014\022\014\n\004time\030\003 \001(\t\"k\n\004Nod" +
      "e\022\014\n\004host\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\022\n\n\002id\030\003 \001(" +
      "\005\022\021\n\tsuccessor\030\004 \001(\t\022\023\n\013successorId\030\005 \001(" +
      "\005\022\023\n\013predecessor\030\006 \001(\t*9\n\013messageType\022\r\n" +
      "\tFIND_HOST\020\000\022\010\n\004DATA\020\001\022\007\n\003ACK\020\002\022\010\n\004INFO\020" +
      "\003*\246\002\n\010infoType\022\r\n\tLIST_NODE\020\000\022\016\n\nDISK_SP" +
      "ACE\020\001\022\020\n\014NUM_REQUESTS\020\002\022\016\n\nLIST_FILES\020\003\022" +
      "\016\n\nNUM_CHUNKS\020\004\022\022\n\016CHUNK_LOCATION\020\005\022\022\n\016R" +
      "ETRIEVE_CHUNK\020\006\022\n\n\006FINGER\020\007\022\017\n\013PREDECESS" +
      "OR\020\010\022\n\n\006UPDATE\020\t\022\034\n\030CLOSEST_PRECEDING_FI" +
      "NGER\020\n\022\010\n\004NODE\020\013\022\t\n\005ASK_M\020\014\022\005\n\001M\020\r\022\021\n\rAS" +
      "K_SUCCESSOR\020\016\022\023\n\017ASK_NODE_DETAIL\020\017\022\026\n\022UP" +
      "DATE_PREDECESSOR\020\020B\022\n\020edu.usfca.cs.dfsb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "Type", "FileName", "TotalChunk", "ChunkId", "Data", });
    internal_static_Info_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Info_descriptor,
        new java.lang.String[] { "Type", "Data", "Time", });
    internal_static_Node_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Node_descriptor,
        new java.lang.String[] { "Host", "Port", "Id", "Successor", "SuccessorId", "Predecessor", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
